 # -*- mode: ruby -*-
 # vi: set ft=ruby :


 Vagrant.configure("2") do |config|
   config.proxy.http     = "http://proxy:8080"
   config.proxy.https    = "http://proxy:8080"
   config.proxy.no_proxy = "localhost,127.0.0.1"
   config.vm.box_check_update = false
   # SSH Settings
   config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key"]
   config.ssh.insert_key = false
   config.vm.define "app" do |app|
     app.vm.hostname = 'app'
     app.vm.box = "centos/7"

     app.vm.network :private_network, ip: "192.168.56.101"


     app.vm.provider :virtualbox do |v|
       v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
       v.customize ["modifyvm", :id, "--memory", 1024]
       v.customize ["modifyvm", :id, "--name", "app"]
     end
   end
 end
